name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.9
  # minimum required dependencies for dask
  - cloudpickle=0.4.0
  - fsspec=0.6.0
  - partd=0.3.10
  - pyyaml
  - toolz=0.8.2
  # test dependencies
  - pytest
  - pytest-rerunfailures
  - pytest-xdist
